#!/bin/bash

CONFIG_DIR="$HOME/.config/waybar"
OUT_FILE="$CONFIG_DIR/colors.css"

# Default fallback values if environment variables aren't set
: "${WAYBAR_DARK0:=rgb(0, 0, 0)}"
: "${WAYBAR_DARK1:=rgb(80, 80, 80)}"
: "${WAYBAR_DARK_BG:=rgb(26, 26, 26)}"
: "${WAYBAR_WHITE0:=rgb(160, 160, 160)}"
: "${WAYBAR_WHITE1:=rgb(220, 220, 220)}"
: "${WAYBAR_LIGHT0:=rgb(235, 235, 235)}"
: "${WAYBAR_LIGHT1:=rgb(245, 245, 245)}"
: "${WAYBAR_LIGHT2:=rgb(255, 255, 255)}"
: "${WAYBAR_ACCENT_BLUE:=rgb(216, 222, 233)}"
: "${WAYBAR_ACCENT_GREEN:=rgb(163, 190, 140)}"
: "${WAYBAR_ACCENT_RED:=rgb(191, 97, 106)}"
: "${WAYBAR_ACCENT_YELLOW:=rgb(235, 203, 139)}"

# Write to colors.css
echo "/* Auto-generated from environment variables */" > "$OUT_FILE"
echo "" >> "$OUT_FILE"
echo "/* Backgrounds and deep shadows */" >> "$OUT_FILE"
echo "@define-color dark0 $WAYBAR_DARK0;" >> "$OUT_FILE"
echo "@define-color dark1 $WAYBAR_DARK1;" >> "$OUT_FILE"
echo "@define-color dark-bg $WAYBAR_DARK_BG;" >> "$OUT_FILE"
echo "" >> "$OUT_FILE"
echo "/* Mid-tones and UI elements */" >> "$OUT_FILE"
echo "@define-color white0 $WAYBAR_WHITE0;" >> "$OUT_FILE"
echo "@define-color white1 $WAYBAR_WHITE1;" >> "$OUT_FILE"
echo "" >> "$OUT_FILE"
echo "/* Highlights and Primary Text */" >> "$OUT_FILE"
echo "@define-color light0 $WAYBAR_LIGHT0;" >> "$OUT_FILE"
echo "@define-color light1 $WAYBAR_LIGHT1;" >> "$OUT_FILE"
echo "@define-color light2 $WAYBAR_LIGHT2;" >> "$OUT_FILE"
echo "" >> "$OUT_FILE"
echo "/* Accent Colors */" >> "$OUT_FILE"
echo "@define-color accent-blue $WAYBAR_ACCENT_BLUE;" >> "$OUT_FILE"
echo "@define-color accent-green $WAYBAR_ACCENT_GREEN;" >> "$OUT_FILE"
echo "@define-color accent-red $WAYBAR_ACCENT_RED;" >> "$OUT_FILE"
echo "@define-color accent-yellow $WAYBAR_ACCENT_YELLOW;" >> "$OUT_FILE"
